### ISSUE TITLE
Suggestions for enhancements to the package list

### ISSUE THREAD

**Issue by lee-dohm** [atom/settings-view#278]
@benogle suggested I share some stuff that I posted in atom/atom#4256 with regard to stylesheet customizations of the package list. I use @postcasio's [enhanced-package-list package](https://atom.io/packages/enhanced-package-list) with the following stylesheet customizations:

```LESS
.octicons(@char) {
  font-family: "Octicons Regular";
  content: @char;
  margin-right: 5px;
}

.settings-view .config-menu .panels-packages {
  // Puts the GitHub icon in front of official Atom packages
  .bundled-package .icon > span:first-child:before {
    .octicons("\f00a");
  }

  // Puts the Bug icon in front of incompatible packages
  .incompatible-package .icon > span:first-child:before {
    .octicons("\f091");
    color: @text-color-error;
  }

  // Grays out and puts a red X icon in front of disabled packages
  .disabled-package {
    opacity: 0.5;

    .icon > span:first-child:before {
      .octicons("\f081");
      color: @text-color-error;
    }
  }

  // Puts a blue Person icon in front of packages that match my GitHub user name
  .author-highlight .icon > span:first-child:before {
    .octicons("\f018");
    color: @text-color-info;
  }

  > li.author-highlight > a {
    color: inherit;

    &:hover {
      color: inherit;
    }

    .package-author {
      color: inherit;
    }
  }
}
```

Which looks like this:

![screen shot 2014-11-21 at 7 29 39 pm](https://cloud.githubusercontent.com/assets/1038121/5152722/d3c6cba6-71b4-11e4-986a-abf1528c9db7.png)

Well, except for the incompatible package one, but I don't have any of them installed ...
