### ISSUE TITLE
Use custom checkbox toggles

### ISSUE THREAD

**Issue by kevinsawicki** [atom/settings-view#296]
Now that the themes are styling the settings view via #277, the checkbox on Mac OS X Mavericks using the default dark theme looses some contrast.

![screen shot 2014-12-24 at 9 23 27 am](https://cloud.githubusercontent.com/assets/671378/5550037/af365136-8b4e-11e4-997f-f2c42f05a66f.png)

Perhaps we should port the custom toggles used in the new one themes as core to the settings view to provide consistency across all platforms.

**Comment by mnquintana** [comment]
It looks a little odd on Yosemite too.

![screenshot 2015-01-07 19 18 53](https://cloud.githubusercontent.com/assets/823545/5655870/1c527408-96a2-11e4-9cd7-bf9277b821b6.png)

**Comment by simurai** [comment]
Activated toggles use the "success" color from themes.

![screen shot 2015-01-09 at 12 40 52 am](https://cloud.githubusercontent.com/assets/378023/5664982/32c183a4-9798-11e4-98ce-db236d0cd87f.png)

**Comment by mnquintana** [comment]
Awesome!!! :smiley:

**Comment by simurai** [comment]
For people that prefer the native checkboxes, here how you can reset them in your `styles.less`:

```css
// Reset to native checkboxes
.settings-view {
  .checkbox {
    padding-left: 20px;
  }
  input[type="checkbox"] {
    all: unset;
    -webkit-appearance: checkbox;
    float: left;
    margin: 2px 0 0 -20px;
    &:before {
      content: none;
    }
  }
}
```

/cc @orderedlist in case you need it for the Unity theme.
