### ISSUE TITLE
Sticky headers

### ISSUE THREAD

**Issue by simurai** [atom/settings-view#344]
From a discussion in #318, if you have a lot of packages installed, it's easy to scroll past the next category (Community, Core, Dev).

An option is to make the headers "sticky", so they stay at the top until you reach the next category.

![sticky](https://cloud.githubusercontent.com/assets/378023/5733045/ca8b82e8-9bdf-11e4-9ceb-29795cf666c1.gif)

**Comment by mnquintana** [comment]
:+1: Yessssss looks good!

**Comment by kevinsawicki** [comment]
Yeah, this is nice :+1:

**Comment by simurai** [comment]
I shouldn't post animated gifs without a deeper look into implementation. :grin: 

I tried the following:

```less
@import "ui-variables";
.settings-view .installed-packages .sub-section-heading {
  @_padding: @component-padding*1.5;
  position: fixed;
  z-index: 1;
  margin: 0 -@_padding;
  top: @tab-height + 1px;
  width: 800px + @_padding*2;
  padding: @_padding;
  border-radius: 0 0 @component-border-radius*2 @component-border-radius*2;
  background-color: lighten(@base-background-color, 4%);
  box-shadow: 0 2px 4px hsla(0,0%,0%,.2);
}
```

using `position: fixed` to pull the header out of the scrolling. But already running into issues:

* The `top` property would need to be calculated by JS, not just because themes might change the tabs height.. also some packages add stuff on top of the tabs.
* `width` doesn't shrink when resizing. We could use `right` but then we would have to calculate `left`, also when resizing.
* Once you make a header fixed, the space used is removed, causing the scroll to jump

Maybe a better option is to clone the headers and have them positioned `absolute` outside of the scrollable `.panels`. Then the size and position is based on the parent?

Anyways, it's not as easy as it first seemed. Chrome once also had a flagged `position: sticky` feature, that would be perfect, but they removed it again. Alternatively we could think about a sub-nav instead.. or wait till we take a look at the "side panel" thing.
